### ISSUE TITLE
Check for active dates

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#19]
Search as many active dates as possible. This checker is intendet for reference or template courses. This kind of courses exists for many years and should't have any definitve dates.

**Comment by adpe** [comment]
Hi @moleculech 

I've just done a code review and correct some stuff. Did you also noticed, that it doesn't matter the configured language in the course or profile and the block always takes the `German` name for the langstring? I've found something here https://moodle.org/mod/forum/discuss.php?d=91157 and I asked in the Telegram Moodle dev chat:

![image](https://user-images.githubusercontent.com/9467708/78909485-e638ad80-7a83-11ea-9717-942c3bac2163.png)

![image](https://user-images.githubusercontent.com/9467708/78900381-1037a300-7a77-11ea-8cfc-b46af8538ff1.png)

I think we need to add more stuff here:
- [x] Disabled it per default in the global settings. As this is more FFHS-specific.
- [x] Add a setting with the available mod activities, so that the user can select which activities should be listed or not.
- [x] Add a setting with the available course categories or `pattern` e.g. Referenzkurse, so that the checker will only be displayed in this courses block.

**Comment by adpe** [comment]
Just done the first task. It would be great to hear, what you think about that solution?

**Comment by adpe** [comment]
Seems to work on my other moodle dev environment @moleculech.

![image](https://user-images.githubusercontent.com/9467708/78922469-dd050c00-7a96-11ea-869f-f801e46804ef.png)

**Comment by adpe** [comment]
Hi  @moleculech 

As we discussed you will fix/add the `MOD_TYPE_QUIZ` to the `resolution_link_helper.php`. I am working on a solution to solve the other two open tasks (https://github.com/ffhs/moodle-block_course_checker/issues/19#issuecomment-611529958).

Greets,
Adrian

**Comment by adpe** [comment]
Hi @moleculech 

The open tasks from this checker are thus completed. Please test and peer-review it.

Cheers,
Adrian

**Comment by adpe** [comment]
Hi @moleculech 

I've done the other open point (https://github.com/ffhs/moodle-block_course_checker/issues/19#issuecomment-618388372) as I want to progress in this issue. For me this story/issue is done and tests were okay. May be good if you can review it?

Feel free after to close that issue and move it to done.
